package com.akqid.zblog.vo;

import java.util.Date;

public class BComment extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.create_by_id
     *
     * @mbg.generated
     */
    private String createById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.create_by_name
     *
     * @mbg.generated
     */
    private String createByName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.update_by_id
     *
     * @mbg.generated
     */
    private String updateById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.update_by_name
     *
     * @mbg.generated
     */
    private String updateByName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_comment.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated
     */
    public BComment(String id, String createById, String createByName, Date createTime, String updateById, String updateByName, Date updateTime, String title, String content, String delFlag, String state) {
        this.id = id;
        this.createById = createById;
        this.createByName = createByName;
        this.createTime = createTime;
        this.updateById = updateById;
        this.updateByName = updateByName;
        this.updateTime = updateTime;
        this.title = title;
        this.content = content;
        this.delFlag = delFlag;
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_comment
     *
     * @mbg.generated
     */
    public BComment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.id
     *
     * @return the value of b_comment.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.id
     *
     * @param id the value for b_comment.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.create_by_id
     *
     * @return the value of b_comment.create_by_id
     *
     * @mbg.generated
     */
    public String getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.create_by_id
     *
     * @param createById the value for b_comment.create_by_id
     *
     * @mbg.generated
     */
    public void setCreateById(String createById) {
        this.createById = createById == null ? null : createById.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.create_by_name
     *
     * @return the value of b_comment.create_by_name
     *
     * @mbg.generated
     */
    public String getCreateByName() {
        return createByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.create_by_name
     *
     * @param createByName the value for b_comment.create_by_name
     *
     * @mbg.generated
     */
    public void setCreateByName(String createByName) {
        this.createByName = createByName == null ? null : createByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.create_time
     *
     * @return the value of b_comment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.create_time
     *
     * @param createTime the value for b_comment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.update_by_id
     *
     * @return the value of b_comment.update_by_id
     *
     * @mbg.generated
     */
    public String getUpdateById() {
        return updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.update_by_id
     *
     * @param updateById the value for b_comment.update_by_id
     *
     * @mbg.generated
     */
    public void setUpdateById(String updateById) {
        this.updateById = updateById == null ? null : updateById.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.update_by_name
     *
     * @return the value of b_comment.update_by_name
     *
     * @mbg.generated
     */
    public String getUpdateByName() {
        return updateByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.update_by_name
     *
     * @param updateByName the value for b_comment.update_by_name
     *
     * @mbg.generated
     */
    public void setUpdateByName(String updateByName) {
        this.updateByName = updateByName == null ? null : updateByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.update_time
     *
     * @return the value of b_comment.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.update_time
     *
     * @param updateTime the value for b_comment.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.title
     *
     * @return the value of b_comment.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.title
     *
     * @param title the value for b_comment.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.content
     *
     * @return the value of b_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.content
     *
     * @param content the value for b_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.del_flag
     *
     * @return the value of b_comment.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.del_flag
     *
     * @param delFlag the value for b_comment.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_comment.state
     *
     * @return the value of b_comment.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_comment.state
     *
     * @param state the value for b_comment.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}